[package]
name = "chatbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
chrono-tz = { version = "0.10.1", features = ["serde"] }
debounce = "0.2.2"
genai = "0.1.19"
poise = "0.6.1"
rand = "0.9.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.19"
