[package]
name = "chatbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
dotenvy_macro = "0.15.7"
regex = "1.11.1"
rig-core = { version = "0.7.0", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.19"
