services:
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        environment:
            QDRANT__SERVICE__GRPC_PORT: "6334"
        volumes:
            - ./qdrant/storage:/qdrant/storage
            - ./qdrant/snapshots:/qdrant/snapshots
            - ./qdrant/config:/qdrant/config

    # TODO
    # chatbot:
    #     build: .
