services:
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        environment:
            QDRANT__SERVICE__GRPC_PORT: "6334"
        volumes:
            - ./qdrant/storage:/qdrant/storage
            - ./qdrant/snapshots:/qdrant/snapshots
            - ./qdrant/config:/qdrant/config

    chatbot:
        build: .
        image: chatbot
        container_name: chatbot
        restart: unless-stopped
        volumes:
            - type: bind
              source: ./config.toml
              target: /config.toml
            - type: bind
              source: ./saves
              target: /saves
        extra_hosts:
            - "host.docker.internal:host-gateway"
